name: Build and Publish to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build with auditwheel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # 可根据需要调整

      - name: Install build tools
        run: |
          pip install build pybind11 scikit-build
          pip install --upgrade pip
          pip install auditwheel

      - name: Build wheel
        run: python -m build

      - name: Show built wheels
        run: ls -lh dist/

      - name: Repair wheel with auditwheel
        run: |
          mkdir -p wheelhouse
          for whl in dist/*.whl; do
            auditwheel repair "$whl" --wheel-dir wheelhouse
          done

      - name: Upload fixed wheels as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fixed-wheels
          path: wheelhouse/

  publish:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    environment:
      name: pypi
      url: https://pypi.org/p/chinese_chess_lib
    permissions:
      id-token: write  # Required for trusted publishing
    steps:
      - name: Download wheels
        uses: actions/download-artifact@v4
        with:
          name: fixed-wheels
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
