name: Build and Publish to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.11, 3.12, 3.13]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build pybind11 scikit-build

      - name: Build wheels
        run: python -m build

      # Linux only
      - name: Repair Linux wheels with auditwheel
        if: matrix.os == 'ubuntu-latest'
        run: |
          pip install auditwheel
          mkdir -p wheelhouse
          for whl in dist/*.whl; do
            auditwheel repair "$whl" --plat manylinux_2_28_x86_64 -w wheelhouse/
          done
        shell: bash

      - name: Move wheels (macOS and Windows)
        if: matrix.os != 'ubuntu-latest'
        run: |
          mkdir -p wheelhouse
          mv dist/*.whl wheelhouse/
        shell: bash

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-py${{ matrix.python-version }}
          path: wheelhouse/

  publish:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      id-token: write  # For PyPI trusted publisher

    steps:
      - name: Download all wheel artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          path: dist/
          merge-multiple: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
